### ISSUE TITLE
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xb3

### ISSUE THREAD

**Issue by napus** [vijishmadhavan/ArtLine#3]
Python 3.9

`ERROR: Command errored out with exit status 1:
     command: 'E:\python_projects\ArtLine\.venv\Scripts\python.exe' 'E:\python_projects\ArtLine\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\PAWE~1\AppData\Local\Temp\tmph2xvoder'
         cwd: C:\Users\Paweł\AppData\Local\Temp\pip-install-68zlosqp\bottleneck
    Complete output (57 lines):
    running dist_info
    creating C:\Users\Paweł\AppData\Local\Temp\pip-install-68zlosqp\bottleneck\pip-wheel-metadata\Bottleneck.egg-info
    writing C:\Users\Paweł\AppData\Local\Temp\pip-install-68zlosqp\bottleneck\pip-wheel-metadata\Bottleneck.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Paweł\AppData\Local\Temp\pip-install-68zlosqp\bottleneck\pip-wheel-metadata\Bottleneck.egg-info\dependency_links.txt
    writing requirements to C:\Users\Paweł\AppData\Local\Temp\pip-install-68zlosqp\bottleneck\pip-wheel-metadata\Bottleneck.egg-info\requires.txt
    writing top-level names to C:\Users\Paweł\AppData\Local\Temp\pip-install-68zlosqp\bottleneck\pip-wheel-metadata\Bottleneck.egg-info\top_level.txt
    writing manifest file 'C:\Users\Paweł\AppData\Local\Temp\pip-install-68zlosqp\bottleneck\pip-wheel-metadata\Bottleneck.egg-info\SOURCES.txt'
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte (sitecustomize.py, line 21)
    Traceback (most recent call last):
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
        main()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\build_meta.py", line 236, in run_setup
        super(_BuildMetaLegacyBackend,
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 196, in <module>
        setup(**metadata)
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\command\dist_info.py", line 31, in run
        egg_info.run()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
        self.find_sources()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
        mm.run()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
        self.add_defaults()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\setuptools\command\egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "C:\Python38\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "C:\Python38\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Python38\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Python38\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "setup.py", line 75, in finalize_options
        import numpy
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "E:\python_projects\ArtLine\.venv\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('E:\\python_projects\\ArtLine\\.venv\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\python_projects\ArtLine\.venv\Scripts\python.exe' 'E:\python_projects\ArtLine\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\PAWE~1\AppData\Local\Temp\tmph2xvoder' Check the logs for full command output.`

**Comment by vijishmadhavan** [comment]
Please check this video, colab instruction.

https://youtu.be/ULqlp6Btk2w
